spring:
  application:
    name: openmsp-kit
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

tmdb:
  api-key: ${TMDB_API_KEY}
  movie-ids-source: ${MOVIE_IDS_SOURCE}
  person-ids-source: ${PERSON_IDS_SOURCE}
  images-dest-path: ${TMDB_IMAGES_DEST_PATH}