package com.msp.openmsp_kit.model.common;

public enum EndPoint {

    // MOVIES
    DETAILS, CREDITS, EXTERNAT_IDS, IMAGES, KEYWORDS,
    LATEST, LISTS, RECOMMENDATIONS, RELEASE_DATES,
    REVIEWS, SIMILAR, TRANSLATIONS, VIDEOS, WATCH_PROVIDERS,
    CHANGES, ALTERNATIVE_TITLES,

    NOW_PLAYING, POPULAR, TOP_RATED, UPCOMING
}
